project_id = "ylngzthselknsackmfge"

[functions.identify-pest]
verify_jwt = false

[functions.weather-advisor]
verify_jwt = false

[functions.crop-health-scanner]
verify_jwt = false

[functions.crop-chatbot]
verify_jwt = false

[functions.crop-advisor]
verify_jwt = false

[functions.crop-simulator]
verify_jwt = false

[functions.harvest-predictor]
verify_jwt = false

[functions.market-advisor]
verify_jwt = false
